name: pos_mobile
description: Invan POS mobile application

version: 1.1.0+9

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.3+2
  mask_text_input_formatter: ^2.4.0
  pinput: ^2.2.12
  flutter_svg: ^2.0.2
  syncfusion_flutter_datepicker: ^20.2.46
  mobile_scanner: ^5.1.1
  fluttertoast: ^8.1.2
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  path_provider: ^2.0.11
  http: ^1.2.0
  syncfusion_flutter_xlsio: ^20.4.38-beta
  open_file: ^3.2.1
  share_plus: ^7.2.1
  cross_file: ^0.3.3+2
  flutter_barcode_listener: ^0.1.3
  visibility_detector: ^0.4.0+2
  intl: ^0.18.0
  bloc: ^8.1.1
  meta: ^1.8.0
  shimmer: ^2.0.0
  flutter_slidable: ^3.0.1
  equatable: ^2.0.5
  converter_uz: ^1.0.1
  dropdown_button2: ^2.3.9
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/product_list.json

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400

        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500

        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
